In [1]:
import numpy as np

In [2]:
def sym(M):
    sym_M = (M + M.T) / 2
    return sym_M


def mat(vec, shape):
        M = vec.reshape(shape, order='F')

        return M

def vec(M):
        v = M.reshape((-1, 1), order='F')
        
        return v


In [3]:
n = 2
k = 3
κ = 1e-4

# X_t: 2x1, W_t: 3x1
ψ_q = κ * np.array([[1.], [2.]])
ψ_x = κ * np.array([[3., 4.],
                    [5., 6.]])
ψ_w = κ * np.array([[7., 8., 9.],
                    [10., 11., 12.]])

ψ_qq = κ * np.array([[13.],
                     [14.]])

ψ_xq = κ * np.array([[15., 16.],
                     [17., 18.]])

ψ_xx = κ * np.array([[19., 20., 21., 22.],
                     [23., 24., 25., 26.]])

ψ_xw = κ * np.array([[27., 28., 29., 30., 31., 32.],
                     [33., 34., 35., 36., 37., 38.]])

ψ_wq = κ * np.array([[39., 40., 41.],
                     [42., 43., 44.]])

ψ_ww = κ * np.array([[45., 46., 47., 48., 49., 50., 51., 52., 53.],
                     [54., 55., 56., 57., 58., 59., 60., 61., 62.]])

# Y_t: 1x1
Γ_0 = κ * np.array([[63.]])

Γ_1 = κ * np.array([[64., 65.]])

Γ_2 = κ * np.array([[66., 67.]])

Γ_3 = κ * np.array([[68., 69., 70., 71.]])

Ψ_0 = κ * np.array([[72., 73., 74.]])

Ψ_1 = κ * np.array([[75., 76., 77., 78., 79., 80.]])

Ψ_2 = κ * np.array([[81., 82., 83., 84., 85., 86., 87., 88., 89.]])

In [4]:
Θ_10 = ψ_q
Θ_11 = ψ_x
Λ_10 = ψ_w
Θ_20 = ψ_qq
Θ_21 = 2 * ψ_xq
Θ_22 = ψ_x
Θ_23 = ψ_xx
Λ_20 = 2 * ψ_wq
Λ_21 = 2 * ψ_xw
Λ_22 = ψ_ww

# $\bar{\Gamma}_0$

In [5]:
modif_Ψ_2 = np.eye(k) - sym(2 * Ψ_2.reshape((k, k), order='F'))
det_term = np.linalg.det(modif_Ψ_2)

In [6]:
Γ_0_bar = Γ_0 - 1 / 2 * np.log(det_term) + 1 / 2 * Ψ_0 @ np.linalg.inv(modif_Ψ_2) @ Ψ_0.T
Γ_0_bar

array([[0.03255799]])

# $\bar{\Gamma}_1$

In [7]:
Γ_1

array([[0.0064, 0.0065]])

In [8]:
Ψ_0 @ np.linalg.inv(modif_Ψ_2) @ mat(Ψ_1, (k, n))

array([[0.00017541, 0.00018233]])

In [9]:
Γ_1_bar = Γ_1 + Ψ_0 @ np.linalg.inv(modif_Ψ_2) @ mat(Ψ_1, (k, n))

In [10]:
Γ_1_bar

array([[0.00657541, 0.00668233]])

# $\bar{\Gamma}_2$

In [11]:
Γ_2_bar = Γ_2

# $\bar{\Gamma}_3$

In [12]:
Γ_3

array([[0.0068, 0.0069, 0.007 , 0.0071]])

In [13]:
1 / 2 * vec(mat(Ψ_1, (k, n)).T @ (np.linalg.inv(modif_Ψ_2)) @ mat(Ψ_1, (k, n))).T

array([[9.13081155e-05, 9.49119506e-05, 9.49119506e-05, 9.86580408e-05]])

In [14]:
Γ_3_bar = Γ_3 + 1 / 2 * vec(mat(Ψ_1, (k, n)).T @ (np.linalg.inv(modif_Ψ_2)) @ mat(Ψ_1, (k, n))).T
Γ_3_bar

array([[0.00689131, 0.00699491, 0.00709491, 0.00719866]])

# $\tilde{\Gamma}_0$

In [15]:
Γ_0_tilde = Γ_0_bar + Γ_1_bar @ Θ_10 + Γ_2_bar @ Θ_20 + Γ_3_bar @ (np.kron(Θ_10, Θ_10))
Γ_0_tilde

array([[0.03257794]])

# $\tilde{\Gamma}_1$

In [16]:
Γ_1_tilde = Γ_1_bar @ Θ_11 + Γ_2_bar @ Θ_21 + Γ_3_bar @ (np.kron(Θ_10, Θ_11) + np.kron(Θ_11, Θ_10))
Γ_1_tilde

array([[4.78971915e-05, 5.18838140e-05]])

# $\tilde{\Gamma}_2$

In [17]:
Γ_2_tilde = Γ_2_bar @ Θ_22
Γ_2_tilde

array([[5.33e-06, 6.66e-06]])

# $\tilde{\Gamma}_3$

In [18]:
Γ_3_tilde = Γ_2_bar @ Θ_23 + Γ_3_bar @ (np.kron(Θ_11, Θ_11))
Γ_3_tilde

array([[2.79545334e-05, 2.92856646e-05, 3.06156626e-05, 3.19470757e-05]])

# $\tilde{\Psi}_0$

In [19]:
Ψ_0_tilde = Γ_1_bar @ Λ_10 + Γ_2_bar @ Λ_20 + Γ_3_bar @ (np.kron(Θ_10, Λ_10) + np.kron(Λ_10, Θ_10))
Ψ_0_tilde

array([[0.00011905, 0.00012304, 0.00012703]])

# $\tilde{\Psi}_1$

In [20]:
Γ_3_bar_product_term = np.kron(Θ_11, Λ_10) + np.hstack([np.kron(Λ_10, Θ_11[:, [j]]) for j in range(n)])

Ψ_1_tilde = Γ_2_bar @ Λ_21 + Γ_3_bar @ Γ_3_bar_product_term

In [21]:
Ψ_1_tilde

array([[7.98792514e-05, 8.25415119e-05, 8.52037725e-05, 8.78640512e-05,
        9.05268753e-05, 9.31896994e-05]])

# $\tilde{\Psi}_2$

In [22]:
Ψ_2_tilde = Γ_2_bar @ Λ_22 + Γ_3_bar @ np.kron(Λ_10, Λ_10)
Ψ_2_tilde

array([[6.59004383e-05, 6.72328397e-05, 6.85652411e-05, 6.98928367e-05,
        7.12255199e-05, 7.25582030e-05, 7.38852351e-05, 7.52182000e-05,
        7.65511650e-05]])